version: '3.4'

services:
  postgres_database:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "6000:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
  
  base-gateway:
    build:
      context: ./APIGateways/BaseGateway
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - user-api
  
  auth-api:
    build:
      context: ./Services/Auth/Auth.API
      dockerfile: Dockerfile
    environment:
      - ConnectionString=Host=postgres_database;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};
      - Jwt_Secret=${JWT_SECRET}
      - Jwt_Issuer=auth-api
      - Jwt_Timeout=${JWT_TIMEOUT}
    ports:
      - "80"
    depends_on:
      - postgres_database

  user-api:
    build:
      context: ./Services/User/User.API
      dockerfile: Dockerfile
    environment:
      - ConnectionString=Host=postgres_database;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};
      - Jwt_Secret=${JWT_SECRET}
      - Jwt_Issuer=auth-api
      - Jwt_Timeout=${JWT_TIMEOUT}
    ports:
      - "80"
    depends_on:
      - postgres_database
      - auth-api
  
  catalog-api:
    build:
      context: ./Services/Catalog/Catalog.API
      dockerfile: Dockerfile
    environment:
      - ConnectionString=Host=postgres_database;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};
      - Jwt_Secret=${JWT_SECRET}
      - Jwt_Issuer=auth-api
      - Jwt_Timeout=${JWT_TIMEOUT}
    ports:
      - "80"
    depends_on:
      - postgres_database
      - auth-api
    
  basket-api:
    build:
      context: ./Services/Basket/Basket.API
      dockerfile: Dockerfile
    environment:
      - ConnectionString=Host=postgres_database;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};
      - Jwt_Secret=${JWT_SECRET}
      - Jwt_Issuer=auth-api
      - Jwt_Timeout=${JWT_TIMEOUT}
    ports:
      - "80"
    depends_on:
      - postgres_database
      - auth-api
        
  order-api:
    build:
      context: ./Services/Order/Order.API
      dockerfile: Dockerfile
    environment:
      - ConnectionString=Host=postgres_database;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};
      - Jwt_Secret=${JWT_SECRET}
      - Jwt_Issuer=auth-api
      - Jwt_Timeout=${JWT_TIMEOUT}
    ports:
      - "80"
    depends_on:
      - postgres_database
      - auth-api

volumes:
  database-data:
