version: '3.4'

services:
  postgres_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
  
  base-gateway:
    build:
      context: ./APIGateways/BaseGateway
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - user-api

  user-api:
    build:
      context: ./Services/User/User.API
      dockerfile: Dockerfile
    environment:
      - ConnectionString=Host=postgres_database;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};
    ports:
      - "80"
    depends_on:
      - postgres_database

volumes:
  database-data:
